gate:
  outer_half_w: 1.35
  outer_half_h: 1.35
  inner_half_w: 0.7
  inner_half_h: 0.7
  poses: []
cam:
  intrinsics:
  - [1.0, 0.0, 0.0]
  - [0.0, 1.0, 0.0]
  - [0.0, 0.0, 1.0]
  extrinsics:
  - [1.0, 0.0, 0.0, 0.0]
  - [0.0, 1.0, 0.0, 0.0]
  - [0.0, 0.0, 1.0, 0.0]
  dist_coeffs: [0.0, 0.0, 0.0, 0.0, 0.0]
  img_w: 640
  img_h: 480
module:
  ransac_thresh: 5.0
